// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtm1_84IfQxhaHCRQGuEFcx8dz0GuEtow',
    appId: '1:1054409979975:web:2393beb796ad45c7e35962',
    messagingSenderId: '1054409979975',
    projectId: 'privy-20773',
    authDomain: 'privy-20773.firebaseapp.com',
    databaseURL: 'https://privy-20773-default-rtdb.firebaseio.com',
    storageBucket: 'privy-20773.firebasestorage.app',
    measurementId: 'G-TD90N3HDK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_BmOfQBJvwNj0dhK9PZAc6dPvI3WyF6s',
    appId: '1:1054409979975:android:b7055312034ed584e35962',
    messagingSenderId: '1054409979975',
    projectId: 'privy-20773',
    databaseURL: 'https://privy-20773-default-rtdb.firebaseio.com',
    storageBucket: 'privy-20773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCc6JlC7tuXWl6h1uf1mHOVskpr5rbLeA',
    appId: '1:1054409979975:ios:253de82c82cbae41e35962',
    messagingSenderId: '1054409979975',
    projectId: 'privy-20773',
    databaseURL: 'https://privy-20773-default-rtdb.firebaseio.com',
    storageBucket: 'privy-20773.firebasestorage.app',
    iosBundleId: 'com.example.privy181125',
  );
}
