name: iOS3-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: pod install
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir -p build/ios/iphoneos/Payload
      - run: cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Zip output
        run: cd build/ios/iphoneos && zip -qr FlutterIpaExport.ipa Payload

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v2.2.5
          overwrite: true
          body: "doctor profile add"
